name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring
          coverage: none
          tools: composer:v2

      - run: composer validate --strict
      - run: composer config repositories.core vcs https://github.com/maeandrew/novaposhta-address-resolver.git
      - run: composer update --prefer-dist --no-interaction --no-progress
      - run: composer quality
