name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['8.2', '8.3']

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring
          coverage: none
          tools: composer:v2

      - run: composer validate --strict
      - run: composer install --prefer-dist --no-interaction --no-progress
      - run: composer test
      - run: composer format:check
      - run: composer analyse
